//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redux.Web.jQuery.Flexigrid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Options {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Options() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Redux.Web.jQuery.Flexigrid.Resources.Options", typeof(Options).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string Align {
            get {
                return ResourceManager.GetString("Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bClass.
        /// </summary>
        internal static string BtnClass {
            get {
                return ResourceManager.GetString("BtnClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buttons.
        /// </summary>
        internal static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colModel.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dataType.
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flexigrid.
        /// </summary>
        internal static string Flexigrid {
            get {
                return ResourceManager.GetString("Flexigrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isdefault.
        /// </summary>
        internal static string Isdefault {
            get {
                return ResourceManager.GetString("Isdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onChangeSort.
        /// </summary>
        internal static string OnChangeSort {
            get {
                return ResourceManager.GetString("OnChangeSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onDragCol.
        /// </summary>
        internal static string OnDragCol {
            get {
                return ResourceManager.GetString("OnDragCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onError.
        /// </summary>
        internal static string OnError {
            get {
                return ResourceManager.GetString("OnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onLoaded.
        /// </summary>
        internal static string OnLoaded {
            get {
                return ResourceManager.GetString("OnLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onpress.
        /// </summary>
        internal static string OnPressCallback {
            get {
                return ResourceManager.GetString("OnPressCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onReload.
        /// </summary>
        internal static string OnReload {
            get {
                return ResourceManager.GetString("OnReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onSubmit.
        /// </summary>
        internal static string OnSubmit {
            get {
                return ResourceManager.GetString("OnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onSuccess.
        /// </summary>
        internal static string OnSuccess {
            get {
                return ResourceManager.GetString("OnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onToggleCol.
        /// </summary>
        internal static string OnToggleCol {
            get {
                return ResourceManager.GetString("OnToggleCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rp.
        /// </summary>
        internal static string RP {
            get {
                return ResourceManager.GetString("RP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchitems.
        /// </summary>
        internal static string SearchItems {
            get {
                return ResourceManager.GetString("SearchItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to separator.
        /// </summary>
        internal static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showTableToggleBtn.
        /// </summary>
        internal static string ShowTableToggleButton {
            get {
                return ResourceManager.GetString("ShowTableToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showToggleBtn.
        /// </summary>
        internal static string ShowToggleBtn {
            get {
                return ResourceManager.GetString("ShowToggleBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to singleSelect.
        /// </summary>
        internal static string SingleSelect {
            get {
                return ResourceManager.GetString("SingleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sortable.
        /// </summary>
        internal static string Sortable {
            get {
                return ResourceManager.GetString("Sortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sortname.
        /// </summary>
        internal static string SortName {
            get {
                return ResourceManager.GetString("SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sortorder.
        /// </summary>
        internal static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usepager.
        /// </summary>
        internal static string UsePager {
            get {
                return ResourceManager.GetString("UsePager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to useRp.
        /// </summary>
        internal static string UseRp {
            get {
                return ResourceManager.GetString("UseRp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
