//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redux.Web.jQuery.Dialog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Options {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Options() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Redux.Web.jQuery.Dialog.Resources.Options", typeof(Options).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoOpen.
        /// </summary>
        internal static string AutoOpen {
            get {
                return ResourceManager.GetString("AutoOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buttons.
        /// </summary>
        internal static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to callback.
        /// </summary>
        internal static string CallbackFunction {
            get {
                return ResourceManager.GetString("CallbackFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closeOnEscape.
        /// </summary>
        internal static string CloseOnEscape {
            get {
                return ResourceManager.GetString("CloseOnEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closeText.
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog.
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialogClass.
        /// </summary>
        internal static string DialogClass {
            get {
                return ResourceManager.GetString("DialogClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled .
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draggable.
        /// </summary>
        internal static string Draggable {
            get {
                return ResourceManager.GetString("Draggable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxHeight.
        /// </summary>
        internal static string MaxHeight {
            get {
                return ResourceManager.GetString("MaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxWidth.
        /// </summary>
        internal static string MaxWidth {
            get {
                return ResourceManager.GetString("MaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minHeight.
        /// </summary>
        internal static string MinHeight {
            get {
                return ResourceManager.GetString("MinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minWidth.
        /// </summary>
        internal static string MinWidth {
            get {
                return ResourceManager.GetString("MinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modal.
        /// </summary>
        internal static string Modal {
            get {
                return ResourceManager.GetString("Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resizable.
        /// </summary>
        internal static string Resizable {
            get {
                return ResourceManager.GetString("Resizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stack.
        /// </summary>
        internal static string Stack {
            get {
                return ResourceManager.GetString("Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zIndex.
        /// </summary>
        internal static string ZIndex {
            get {
                return ResourceManager.GetString("ZIndex", resourceCulture);
            }
        }
    }
}
