//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redux.Web.jQuery.SmartTextBox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Options {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Options() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Redux.Web.jQuery.SmartTextBox.Resources.Options", typeof(Options).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autocomplete.
        /// </summary>
        internal static string Autocomplete {
            get {
                return ResourceManager.GetString("Autocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autocompleteUrl.
        /// </summary>
        internal static string AutocompleteUrl {
            get {
                return ResourceManager.GetString("AutocompleteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autocompleteValues.
        /// </summary>
        internal static string AutocompleteValues {
            get {
                return ResourceManager.GetString("AutocompleteValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caseSensitive.
        /// </summary>
        internal static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to containerClass.
        /// </summary>
        internal static string ContainerClass {
            get {
                return ResourceManager.GetString("ContainerClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editOnDoubleClick.
        /// </summary>
        internal static string EditOnDoubleClick {
            get {
                return ResourceManager.GetString("EditOnDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editOnFocus.
        /// </summary>
        internal static string EditOnFocus {
            get {
                return ResourceManager.GetString("EditOnFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fullSearch.
        /// </summary>
        internal static string FullSearch {
            get {
                return ResourceManager.GetString("FullSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hideEmptyInputs.
        /// </summary>
        internal static string HideEmptyInputs {
            get {
                return ResourceManager.GetString("HideEmptyInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highlight.
        /// </summary>
        internal static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxResults.
        /// </summary>
        internal static string MaxResults {
            get {
                return ResourceManager.GetString("MaxResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minSearchLength.
        /// </summary>
        internal static string MinSearchLength {
            get {
                return ResourceManager.GetString("MinSearchLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onlyAutocomplete.
        /// </summary>
        internal static string OnlyAutocomplete {
            get {
                return ResourceManager.GetString("OnlyAutocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to placeholder.
        /// </summary>
        internal static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to separator.
        /// </summary>
        internal static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smartTextBox.
        /// </summary>
        internal static string SmartTextBox {
            get {
                return ResourceManager.GetString("SmartTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submitChars.
        /// </summary>
        internal static string SubmitChars {
            get {
                return ResourceManager.GetString("SubmitChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submitKeys.
        /// </summary>
        internal static string SubmitKeys {
            get {
                return ResourceManager.GetString("SubmitKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uniqueValues.
        /// </summary>
        internal static string UniqueValues {
            get {
                return ResourceManager.GetString("UniqueValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updateOriginal.
        /// </summary>
        internal static string UpdateOriginal {
            get {
                return ResourceManager.GetString("UpdateOriginal", resourceCulture);
            }
        }
    }
}
